name: story_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.4
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  http: ^1.3.0
  image: ^4.5.4
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  location: ^8.0.0
  geocoding: ^3.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  generate: true
